### ISSUE TITLE
Porting to supported version of justdelete.me

### ISSUE THREAD

**Issue by tupaschoal** [jdm-contrib/justdelete.me-firefox-addon#1]
The main justdelete.me repository has been abandoned and we're trying to keep it alive on a detached fork [here](https://github.com/jdm-contrib), would you be interested in transferring the repo to the jdm-contrib organization? 

If we do we can assure it is kept up-to-date and, since we have gathered some people on the org, not let the project get stale.

Thanks :)

**Comment by rugk** [comment]
Actually maybe merging this extension with the [chrome one](https://github.com/MikeRogers0/justdelete.me-chrome-extension) would also be a good idea, as they are both WebExtensions and could be made to work with both browsers.

**Comment by alaouy** [comment]
@tupaschoal Thanks for taking initiative, as long as the repo will be still be credited to me I'm willing to transfer the repo to you guys.

**Comment by tupaschoal** [comment]
Hey @alaouy,

As you can see on our justdelete.me repo, we didn't change the crediting at all. I see you have yours on the LICENSE, maybe you want to include something in the readme?

Besides that, the commit history will always be there.

Thanks!

**Comment by alaouy** [comment]
@tupaschoal I didn't have write permission to transfer the repo to the organization so I put it under your name, please take care of it ;)

**Comment by tupaschoal** [comment]
Ok @alaouy , it is done now, thanks :)
