### ISSUE TITLE
Update taskbar icon

### ISSUE THREAD

**Issue by psjnek** [jdm-contrib/justdelete.me-firefox-addon#12]
I have some ideas for redesigning the taskbar icons for this project.
I changed the colors to the jdm color palette in GIMP.

Now:
![image](https://user-images.githubusercontent.com/94064167/236611527-6d859979-8f98-4272-93b1-7cf81902b931.png)

After:
![image](https://user-images.githubusercontent.com/94064167/236611541-d46a8708-2dca-4d3f-a150-e62181ce363b.png)

Let me know what you think about it and I might apple the style to the other icons.
@tupaschoal

**Comment by tupaschoal** [comment]
I like it, can you post before/after of all of the icons?

**Comment by psjnek** [comment]
> I like it, can you post before/after of all of the icons?

Here you go.

| Difficulty | Before | After|
| --------------| ---------- | ------ |
| Easy | ![image](https://user-images.githubusercontent.com/94064167/236633889-6feabed8-90a8-49d8-9997-4803f74188f2.png) | ![easy](https://user-images.githubusercontent.com/94064167/236621574-e70acf02-1714-444c-b764-053052a6e03f.png) |
| Medium | ![image](https://user-images.githubusercontent.com/94064167/236633908-bc62bb68-0b24-414d-9865-eeb4780bac63.png) | ![medium](https://user-images.githubusercontent.com/94064167/236621585-b420c29d-ebe2-432b-920f-e1693ad4b0b4.png) |
|Hard | ![image](https://user-images.githubusercontent.com/94064167/236633937-78073eb6-240d-40a6-8cd3-d10772c5b7d2.png) | ![hard](https://user-images.githubusercontent.com/94064167/236621595-0f79f62c-f560-4336-9429-1315d9f5f41a.png) |
| Impossible | ![image](https://user-images.githubusercontent.com/94064167/236633988-fa21890a-307e-40f0-a7af-77ca1501cf34.png) | ![impossible](https://user-images.githubusercontent.com/94064167/236621611-98818354-4ae9-427a-b9aa-b93e222d0af2.png) |
| Limited | ![image](https://user-images.githubusercontent.com/94064167/236634471-d8483970-6418-4675-8006-4da5a9f90730.png) | ![limited](https://user-images.githubusercontent.com/94064167/236634484-601a1696-27eb-4b0a-8c08-edfe0b35a433.png) |
| X | ![image](https://user-images.githubusercontent.com/94064167/236635407-622d2879-32ac-4aeb-be87-b677237ce5ec.png) | ![x](https://user-images.githubusercontent.com/94064167/236635454-e84ef6f2-53af-49c5-9b68-f61b29626a5e.png) |

**Comment by psjnek** [comment]
I will open a PR once you are satisfied with the icons.

**Comment by AlexanderEpolite** [comment]
Looks good to me!  Make a PR and I'll merge it.

Just curious, why the change from cyan to purple on limited?

**Comment by psjnek** [comment]
> Just curious, why the change from cyan to purple on limited?

I changed it because I wanted to match the design language of the jdm website with its browser extension.

![image](https://user-images.githubusercontent.com/94064167/236662866-bffec524-1098-4340-b0e1-752591709c7a.png)

**Comment by psjnek** [comment]
> Looks good to me! Make a PR and I'll merge it.

There you, it is on #14.

**Comment by tupaschoal** [comment]
I like it
