### ISSUE TITLE
Readme/repo needs updating

### ISSUE THREAD

**Issue by PyroSamurai** [jdm-contrib/justdelete.me-firefox-addon#2]
Readme and other links in the repo need to be updated to be correlated with its new location in the Contrib Group

**Comment by AlexanderEpolite** [comment]
Does this still need to be fixed in the new readme?

**Comment by Nightfirecat** [comment]
No, this should be taken care of; this was an issue from quite some time ago.

**Comment by PyroSamurai** [comment]
So long ago that I forgot about it.
