### ISSUE TITLE
Firefox Addon Resurrection

### ISSUE THREAD

**Issue by Nightfirecat** [jdm-contrib/justdelete.me-firefox-addon#4]
To my knowledge, per jdm-contrib/jdm#181, this addon does not work currently, and will not work due to the way Firefox has changed their handling of extensions. With that said, what we have present in the Chrome extension repo may actually work with little-to-no changes for Firefox. (research needed)

**Comment by Nightfirecat** [comment]
From some brief testing I've done today, it seems that the Chrome extension works out-of-the-box for Firefox >57, so we may want to archive this repository and release the Chrome extension for Firefox as well.

**Comment by tupaschoal** [comment]
That sounds great and would also be better for us to maintain just one in the long term.
