### ISSUE TITLE
mdn dead

### ISSUE THREAD

**Issue by hacknorris-code** [jdm-contrib/justdelete.me-firefox-addon#6]
would you just bring it back instead of giving 404? pls...

**Comment by tupaschoal** [comment]
What is it that is not working?

**Comment by hacknorris-code** [comment]
just download site not working and compiling addon by myself leads to unsigned addon =]

**Comment by hacknorris-code** [comment]
(aka - got 404 on firefox addons)

**Comment by tupaschoal** [comment]
Though we got this into our `jdm-contrib` organization, we never really updated the repo to match the new website and redeployed the app.

This doesn't seem like a lot of work, would you be able to do it please @alaouy ?

**Comment by alaouy** [comment]
@tupaschoal The extension was removed from the Mozilla extension store and I no longer have access to that account.
@hacknorris-aka-penguin I doubt that the app in its current state is still compatible with the recent versions of Firefox. Testing and PRs are welcome in this regard and feel free to republish the extension on the store ;)

Cheers

**Comment by AlexanderEpolite** [comment]
> @tupaschoal The extension was removed from the Mozilla extension store and I no longer have access to that account. @hacknorris-aka-penguin I doubt that the app in its current state is still compatible with the recent versions of Firefox. Testing and PRs are welcome in this regard and feel free to republish the extension on the store ;)
> 
> Cheers

I made a new extension for JustDeleteMe.  It is available on Firefox and open-source: https://github.com/alexanderepolite/JustDeleteMe-extension

I'm not very good with maintaining code, so I decided to make a new one while using some parts of this repo.  Let me know what you think :)
