### ISSUE TITLE
I made a new extension

### ISSUE THREAD

**Issue by AlexanderEpolite** [jdm-contrib/justdelete.me-firefox-addon#7]
Since this repo seems inactive and the codebase isn't super clean, I made an extension that uses JustDeleteMe.

https://github.com/alexanderepolite/JustDeleteMe-extension

Let me know what you think!

**Comment by tupaschoal** [comment]
Nice, I don't get why it's incompatible with chromium based browsers and still works on Firefox, isn't it chromium based too?

**Comment by AlexanderEpolite** [comment]
> Nice, I don't get why it's incompatible with chromium based browsers and still works on Firefox, isn't it chromium based too?

No, FF isn't chromium.  AFAIK they use the same methods for extensions, but Firefox is stuck on manifest v2 while Chrome has deprecated v2 and does not allow any new v2 extensions as they have moved on to v3.

Interesting read: https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/

There are programs to compile for both browser types (like uBlock Origin uses), but there is already a Chrome extension on the store, so I didn't bother.

**Comment by tupaschoal** [comment]
Sorry for taking a while to answer @alexanderepolite . 

Your extension seems to work fine, wouldn't you want to merge your implementation into this repository and become a maintainer of it, given Mustapha's answer on the #6 issue? That convergence seems like it would be beneficial to everyone.

Let me know what you think, thanks!

**Comment by AlexanderEpolite** [comment]
> Sorry for taking a while to answer @alexanderepolite .
> 
> Your extension seems to work fine, wouldn't you want to merge your implementation into this repository and become a maintainer of it, given Mustapha's answer on the #6 issue? That convergence seems like it would be beneficial to everyone.
> 
> Let me know what you think, thanks!

Sounds good, but I am not sure how I should merge it into an existing repository.  If you could let me know how or just replace the files in this repo with mine that would be great.  Feel free to remove the `.github` directory, I will update the extension manually instead.

**Comment by tupaschoal** [comment]
I think just making a PR where you replace everything (but the LICENSE) with your version

**Comment by tupaschoal** [comment]
Hi @alexanderepolite , still up for it?

**Comment by AlexanderEpolite** [comment]
> Hi @alexanderepolite , still up for it?

Yes, I hadn't had the time to do it before, I will make a PR soon.  Thank you for reminding me lol

**Comment by tupaschoal** [comment]
Hi Alexander, just dropping by to ask whether you're still interested in doing this :)

**Comment by AlexanderEpolite** [comment]
Hey @tupaschoal , been really busy with classes and other stuff.  I'll make a PR today since I have free time.
