### ISSUE TITLE
kraken.com gets mistaken for gitkraken.com

### ISSUE THREAD

**Issue by array-in-a-matrix** [jdm-contrib/justdelete.me-firefox-addon#9]
This seems to be a problem on only [www.kraken.com](https://www.kraken.com) as [support.kraken.com](https://support.kraken.com) is detected correctly.

![image](https://user-images.githubusercontent.com/78233840/222864161-6b8fa889-cb23-4175-a1dc-e5a406de2e71.png)

**Comment by AlexanderEpolite** [comment]
Are you sure this is for this extension, and not another JustDeleteMe extension?

The extension this repository maintains is here: https://addons.mozilla.org/en-US/firefox/addon/justdeleteme/

**Comment by array-in-a-matrix** [comment]
you are right, looks like I have mistaken this repo for this extension: https://addons.mozilla.org/en-US/firefox/addon/just-delete-me
